version: '1'
services:
  eclipse-temurin:
    image: eclipse-temurin:latest
  nginx:
    image: nginx:latest
    ports:
      - "9443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - eclipse-temurin